In [6]:
# démo gen_test
from pyheatmy import *
import matplotlib.pyplot as plt
import numpy as np

In [2]:
t_debut = (2010, 12, 1)
t_fin = (2010, 12, 30, 23, 59, 59)
dt = 15*60 # pas de temps en (s)

T_riv_amp = 2
T_riv_offset = 12
P_T_riv = 24*4*dt

T_aq_amp = 0
T_aq_offset = 12
P_T_aq = 9999 # à mettre dans le init

dH_amp = 0.1
dH_offset = 0
P_dh = 14*24*4*dt

In [8]:
time_series_dict = {
	"param_time_dates": None,#[t_debut, t_fin, dt], 
    "param_dH_signal": [dH_amp, P_dh, dH_offset], #En vrai y aura une 4e valeur ici mais ca prendra en charge pareil
	"param_T_riv_signal": [T_riv_amp, P_T_riv, T_riv_offset],
    "param_T_aq_signal": [T_aq_amp, P_T_aq, T_aq_offset],
    "sigma_meas_P": None,
    "sigma_meas_T": None, #float
}

emu_observ_test = Time_series.from_dict(time_series_dict)

NameError: name 'dH_amp' is not defined

In [4]:
emu_observ_test._generate_dates_series()
emu_observ_test._dates

array([datetime.datetime(2010, 12, 1, 0, 0),
       datetime.datetime(2010, 12, 1, 0, 15),
       datetime.datetime(2010, 12, 1, 0, 30), ...,
       datetime.datetime(2010, 12, 30, 23, 15),
       datetime.datetime(2010, 12, 30, 23, 30),
       datetime.datetime(2010, 12, 30, 23, 45)], dtype=object)

In [5]:
emu_observ_test._generate_Temp_riv_series()
emu_observ_test._T_riv

array([14.        , 13.99571785, 13.98288972, ..., 13.96157056,
       13.98288972, 13.99571785])

In [6]:
emu_observ_test._generate_Temp_aq_series()
emu_observ_test._T_aq

array([12., 12., 12., ..., 12., 12., 12.])

In [7]:
emu_observ_test._generate_dH_series()
emu_observ_test._dH

[(datetime.datetime(2010, 12, 1, 0, 0), (0.1, 14.0)),
 (datetime.datetime(2010, 12, 1, 0, 15),
  (0.09999890722585104, 13.995717846477207)),
 (datetime.datetime(2010, 12, 1, 0, 30),
  (0.09999562892728728, 13.98288972274762)),
 (datetime.datetime(2010, 12, 1, 0, 45),
  (0.0999901651759575, 13.96157056080646)),
 (datetime.datetime(2010, 12, 1, 1, 0),
  (0.09998251609127465, 13.931851652578137)),
 (datetime.datetime(2010, 12, 1, 1, 15),
  (0.09997268184041314, 13.89386025899021)),
 (datetime.datetime(2010, 12, 1, 1, 30),
  (0.09996066263830529, 13.847759065022574)),
 (datetime.datetime(2010, 12, 1, 1, 45),
  (0.09994645874763658, 13.793745483065376)),
 (datetime.datetime(2010, 12, 1, 2, 0),
  (0.09993007047883985, 13.732050807568877)),
 (datetime.datetime(2010, 12, 1, 2, 15),
  (0.0999114981900887, 13.66293922460509)),
 (datetime.datetime(2010, 12, 1, 2, 30),
  (0.09989074228728942, 13.58670668058247)),
 (datetime.datetime(2010, 12, 1, 2, 45),
  (0.0998678032240723, 13.503679614957955)),

In [8]:
emu_observ_test._generate_Temp_series()
emu_observ_test._T_vir

[(datetime.datetime(2010, 12, 1, 0, 0), array([14.,  0.,  0.,  0., 12.])),
 (datetime.datetime(2010, 12, 1, 0, 15),
  array([13.99571785,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 0, 30),
  array([13.98288972,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 0, 45),
  array([13.96157056,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 1, 0),
  array([13.93185165,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 1, 15),
  array([13.89386026,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 1, 30),
  array([13.84775907,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 1, 45),
  array([13.79374548,  0.        ,  0.        ,  0.        , 12.        ])),
 (datetime.datetime(2010, 12, 1, 2, 0),
  array([13.73205081,  0.        ,  0.        ,  0.        ,